---
title:               on thoughts
tagline:             dev. design. sts.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "ryanRich" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "youareme" %>
name:                Ryan Rich
twitter:             ryanSrich
github:              rr1000
email:               rrichrs@gmail.com
google_analytics_id: YOUR_GA_ID